FROM python:3.12.4-alpine3.20

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN apk add --no-cache libc-dev gcc

RUN pip install -r requirements.txt

COPY . .

# Create a Gunicorn configuration file
RUN echo "bind = '0.0.0.0:8000'" > gunicorn.conf.py
RUN echo "workers = 3" >> gunicorn.conf.py
RUN echo "user = 'www-data'" >> gunicorn.conf.py
RUN echo "group = 'www-data'" >> gunicorn.conf.py

EXPOSE 8000

# Use Gunicorn to run the Django application
CMD ["gunicorn", "--config", "gunicorn.conf.py", "myproject.wsgi:application"]

