# Generated by Django 5.0.3 on 2024-06-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entradaYSalidaDeMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.IntegerField()),
                ('equipo', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('sello', models.CharField(max_length=20)),
                ('rotura', models.CharField(max_length=50)),
                ('fecha_entrada', models.DateField()),
                ('entrega_entrada', models.CharField(max_length=20)),
                ('recibe_entrada', models.CharField(max_length=20)),
                ('firma_entrada', models.BooleanField()),
                ('fecha_reparacion', models.DateField()),
                ('entrega_reparacion', models.CharField(max_length=20)),
                ('recibe_reparacion', models.CharField(max_length=20)),
                ('firma_reparacion', models.BooleanField()),
                ('fecha_salida', models.DateField()),
                ('entrega_salida', models.CharField(default='prueba', max_length=20)),
                ('recibe_salida', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='interrupcione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('problema', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20)),
                ('defectado', models.CharField(max_length=20)),
                ('solucionado', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('observaciones', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='resumenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informatica', models.CharField(max_length=5)),
            ],
        ),
    ]
