# Generated by Django 5.0.3 on 2024-06-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agrupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='audiovisuale',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('agrupacion', models.CharField(max_length=20)),
                ('asignacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('no_inventario', models.CharField(blank=True, max_length=20, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=20, null=True)),
                ('sello', models.CharField(blank=True, max_length=20, null=True)),
                ('fisico', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('observaciones', models.CharField(max_length=50)),
                ('ultima_ubicacion', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('ultima_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField()),
                ('especialidad', models.CharField(max_length=10)),
                ('noCATE', models.PositiveIntegerField()),
                ('fechaCATE', models.DateField()),
                ('tipo_de_medio', models.CharField(max_length=50)),
                ('no_inventario', models.CharField(blank=True, max_length=20, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=20, null=True)),
                ('sello', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(max_length=20)),
                ('defecto', models.CharField(max_length=50)),
                ('fechaSalida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='comunicacione',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('agrupacion', models.CharField(max_length=20)),
                ('asignacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('no_inventario', models.CharField(blank=True, max_length=20, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=20, null=True)),
                ('sello', models.CharField(blank=True, max_length=20, null=True)),
                ('fisico', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('observaciones', models.CharField(max_length=50)),
                ('ultima_ubicacion', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('ultima_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='informatica',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('agrupacion', models.CharField(max_length=20)),
                ('asignacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('no_inventario', models.CharField(blank=True, max_length=20, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=20, null=True)),
                ('sello', models.CharField(blank=True, max_length=20, null=True)),
                ('fisico', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('observaciones', models.CharField(max_length=50)),
                ('ultima_ubicacion', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('ultima_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='utilesHerramienta',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('agrupacion', models.CharField(max_length=20)),
                ('asignacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('no_inventario', models.CharField(blank=True, max_length=20, null=True)),
                ('no_serie', models.CharField(blank=True, max_length=20, null=True)),
                ('sello', models.CharField(blank=True, max_length=20, null=True)),
                ('fisico', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('observaciones', models.CharField(max_length=50)),
                ('ultima_ubicacion', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('ultima_fecha', models.DateField()),
            ],
        ),
    ]
