# Generated by Django 5.0.3 on 2024-06-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlDeMedios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='utilesHerramienta',
            new_name='utilesYHerramienta',
        ),
    ]
