# Generated by Django 5.0.3 on 2024-06-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlDeMedios', '0002_rename_utilesherramienta_utilesyherramienta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agrupacion',
            new_name='agrupaciones',
        ),
    ]
