# Generated by Django 5.0.4 on 2024-06-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlDeMedios', '0003_rename_agrupacion_agrupaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate',
            name='fechaCATE',
            field=models.DateField(verbose_name='fecha CATE'),
        ),
        migrations.AlterField(
            model_name='cate',
            name='fechaSalida',
            field=models.DateField(verbose_name='fecha de salida'),
        ),
        migrations.AlterField(
            model_name='cate',
            name='noCATE',
            field=models.PositiveIntegerField(verbose_name='no CATE'),
        ),
    ]
