# Generated by Django 5.0.4 on 2024-06-29 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlDeMedios', '0004_alter_cate_fechacate_alter_cate_fechasalida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovisuale',
            name='agrupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlDeMedios.agrupaciones'),
        ),
    ]
