# Generated by Django 5.0.4 on 2024-06-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlDeMedios', '0005_alter_audiovisuale_agrupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rama', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='cate',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlDeMedios.especialidades'),
        ),
    ]
